### ISSUE TITLE
Crash when pushing button "Download" for Cover download from amazon for a book - Ubuntu 18.04 / Version 2018.10.01

### ISSUE THREAD

**Issue by sit42** [textbrowser/biblioteq#41] opened 2018-11-05 12:11 UTC
We are using
BiblioteQ Version 2018.10.01
Architecture __amd64__.
Compiled on Oct 2 2018, 07:19:00.
Copyright (c) 2005 - present, Mushroom.
Poppler version 0.62.0.
Qt version 5.9.5 (runtime 5.11.2).
YAZ version 5.19.2.

Downloaded as a deb archive for ubuntu. 18.04.
Installing was easy and running and starting with a new sqlite db worked.
Entering a new book based on ISBN number using SRU search also worked.
Then we wante dto download the cover using amazon. 

But as we hit the "Downlaod" Button for this book, it crashed wit hthe following backtrace:
-----
Application: BiblioteQ (BiblioteQ), signal: Segmentation fault
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Current thread is 1 (Thread 0x7f6d9e314bc0 (LWP 22811))]

Thread 4 (Thread 0x7f6d73ba1700 (LWP 22816)):
#0  0x00007f6d9b287bf9 in __GI___poll (fds=0x7f6d6c000b20, nfds=1, timeout=2212) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f6d9830c439 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f6d9830c54c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f6d9bdda53b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007f6d9bd7e7fa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f6d9bba9bba in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007f6d9bbb4adb in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007f6d9abbd6db in start_thread (arg=0x7f6d73ba1700) at pthread_create.c:463
#8  0x00007f6d9b29488f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7f6d80a5c700 (LWP 22813)):
#0  0x00007f6d9b287bf9 in __GI___poll (fds=0x7f6d7c01a5e0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f6d9830c439 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f6d9830c54c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f6d9bdda53b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007f6d9bd7e7fa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f6d9bba9bba in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007f6d922b3e45 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#7  0x00007f6d9bbb4adb in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007f6d9abbd6db in start_thread (arg=0x7f6d80a5c700) at pthread_create.c:463
#9  0x00007f6d9b29488f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7f6d8ec76700 (LWP 22812)):
#0  0x00007f6d9b287bf9 in __GI___poll (fds=0x7f6d8ec75d28, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f6d93848747 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007f6d9384a36a in xcb_wait_for_event () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007f6d927b5ed9 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#4  0x00007f6d9bbb4adb in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f6d9abbd6db in start_thread (arg=0x7f6d8ec76700) at pthread_create.c:463
#6  0x00007f6d9b29488f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7f6d9e314bc0 (LWP 22811)):
[KCrash Handler]
#6  0x00007f6d9d112ebb in QWidget::windowTitle() const () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007f6d9d11be9e in QWidget::setWindowTitle(QString const&) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x000055c92e8ecf8d in biblioteq_book::slotDownloadImage() ()
#9  0x000055c92e9ec64d in biblioteq_book::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#10 0x00007f6d9bdaf565 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007f6d9d1d0fb2 in QAbstractButton::clicked(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007f6d9d1d11ca in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007f6d9d1d25aa in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007f6d9d1d279d in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007f6d9d12aa98 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007f6d9d0ebe1c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007f6d9d0f3f87 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007f6d9bd804d8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007f6d9d0f28d2 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007f6d9d145c13 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007f6d9d148229 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007f6d9d0ebe1c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007f6d9d0f33ef in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007f6d9bd804d8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00007f6d9c8ef7bb in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#26 0x00007f6d9c8f1335 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#27 0x00007f6d9c8c9f5b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#28 0x00007f6d9284176b in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#29 0x00007f6d9bd7e7fa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#30 0x00007f6d9bd879c0 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#31 0x000055c92e85d4ec in main ()
-----

Is there any workarounf for this? 
Or maybe we have installed something wrong?

PS: WE are not using any ".conf" file yet.

Thank you very much for any help.

**Comment by sit42** [comment] 2018-11-05 12:15
Good news:
After downloading the original "biblioteq.conf" file from source repo and using this, it works!

So it seems this happens only, when there is no .conf file available.

**Comment by textbrowser** [comment] 2018-11-05 16:08
OK, thank you. Will look.

**Comment by textbrowser** [comment] 2018-11-05 20:44
Alright, so I was not able to reproduce this error. I removed biblioteq.conf. I also removed specific entries from the file.

I've added some pointer guards.

**Comment by textbrowser** [comment] 2018-11-05 20:47
I'm testing with Qt 5.11.1.

**Comment by textbrowser** [comment] 2018-11-05 20:47
Now with Qt 4.8.7.

**Comment by textbrowser** [comment] 2018-11-06 00:54
I've reviewed the logic and I'm not able to find a cause. Some other guards have been added.

**Comment by sit42** [comment] 2018-11-06 07:16
We have installed the QT libs 4.8.7 and 5.11.2.

`ldd /usr/local/biblioteq/BiblioteQ 
        linux-vdso.so.1 (0x00007fff22bde000)
        libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f1496ea3000)
        libyaz.so.5 => /usr/lib/libyaz.so.5 (0x00007f1496adb000)
        libQt5PrintSupport.so.5 => /usr/lib/x86_64-linux-gnu/libQt5PrintSupport.so.5 (0x00007f1496866000)
        libQt5Widgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00007f1496011000)
        libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007f149586a000)
        libQt5Network.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007f14954d7000)
        libQt5Sql.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Sql.so.5 (0x00007f149528d000)
        libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007f1494b85000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f14947fc000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f14945e4000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f14941f3000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1493e55000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1493c36000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1493a32000)
        libgnutls.so.30 => /usr/lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007f14936cd000)
        libwrap.so.0 => /lib/x86_64-linux-gnu/libwrap.so.0 (0x00007f14934c3000)
        libexslt.so.0 => /usr/lib/x86_64-linux-gnu/libexslt.so.0 (0x00007f14932ad000)
        libxslt.so.1 => /usr/lib/x86_64-linux-gnu/libxslt.so.1 (0x00007f1493070000)
        libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f1492caf000)
        libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007f1492a23000)
        libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f14927f1000)
        libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f1492553000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f1492336000)
        libicui18n.so.60 => /usr/lib/x86_64-linux-gnu/libicui18n.so.60 (0x00007f1491e95000)
        libicuuc.so.60 => /usr/lib/x86_64-linux-gnu/libicuuc.so.60 (0x00007f1491ade000)
        libpcre2-16.so.0 => /usr/lib/x86_64-linux-gnu/libpcre2-16.so.0 (0x00007f1491867000)
        libdouble-conversion.so.1 => /usr/lib/x86_64-linux-gnu/libdouble-conversion.so.1 (0x00007f1491656000)
        libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f1491340000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f149764d000)
        libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f1491011000)
        libidn2.so.0 => /usr/lib/x86_64-linux-gnu/libidn2.so.0 (0x00007f1490df4000)
        libunistring.so.2 => /usr/lib/x86_64-linux-gnu/libunistring.so.2 (0x00007f1490a76000)
        libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f1490863000)
        libnettle.so.6 => /usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007f149062d000)
        libhogweed.so.4 => /usr/lib/x86_64-linux-gnu/libhogweed.so.4 (0x00007f14903f9000)
        libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f1490178000)
        libnsl.so.1 => /lib/x86_64-linux-gnu/libnsl.so.1 (0x00007f148ff5e000)
        libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f148fc43000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f148fa1d000)
        libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007f148f7ec000)
        libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007f148f536000)
        libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f148f282000)
        libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f148f055000)
        libicudata.so.60 => /usr/lib/x86_64-linux-gnu/libicudata.so.60 (0x00007f148d4ac000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f148d23a000)
        libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f148d032000)
        libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f148ce1d000)
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f148cae5000)
        libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f148c8bd000)
        libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f148c6b9000)
        libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f148c4b3000)
        libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f148c29e000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f148c096000)`

**Comment by textbrowser** [comment] 2018-11-06 15:33
There is a slight probability that an object is accessed incorrectly. The correction will be included in the next release. Closing!

**Closed by textbrowser** 2018-11-06 15:33 UTC

**Comment by textbrowser** [comment] 2018-11-06 15:36
https://github.com/textbrowser/biblioteq/commit/5e3dc543f77876f92016e971d3f2f1dd6f739455
