### ISSUE TITLE
Export /Import Csv with fields containing hypertext links.

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#381] opened 2024-10-15 16:21 UTC
Documents that have in the “keywords” area
“cheese".
“desserts”.
so 2 hypetext links

how to export in csv so that the 2 keywords remain distinct when imported?

Currently, it becomes “cheese desserts” and not “cheese” and “desserts”. 

Thanks in advance for the ideas

**Comment by textbrowser** [comment] 2024-10-15 16:58
You got problems. **Export from BQ and then import into BQ is illogical**. It is not a symmetric operation. Can't export image data for example. And the export is of what you see. So you see a Category column with many newlines in the database presented as one with many spaces in the table. The alternate is then not present with many spaces (wide column) and instead present with many newlines (tall column). Either is ugly because of lots of characters. Export is tabular not database because SQLite has better database export.

Then the import. Doesn't know what is a newline and what is a space. Since you have spaces in column, can't add newlines in export.

Cannot do database export because then it is duplicating the database engines; yes, engines. And that is not BQ.

So only solution is then display tall or wide columns. That is only software solution because, again, **not exporting via the database**. Other is that you correct the import file.

**Comment by textbrowser** [comment] 2024-10-15 17:02
You have one row occupy one screen because of many newlines. Ugly. You have wide columns and many visible rows. Less ugly.

**Comment by meteos77** [comment] 2024-10-15 17:05
my problem has more to do with the hypertext link no longer working.

**Comment by textbrowser** [comment] 2024-10-15 17:05
Nah, not the problem. The problem is that it was two values and now is one value.

**Comment by meteos77** [comment] 2024-10-15 17:06
> Other is that you correct the data after import.

What does it mean to correct?

**Comment by meteos77** [comment] 2024-10-15 17:07
How to import 2 values into hypertext fields?

**Comment by textbrowser** [comment] 2024-10-15 17:09
I explained the solution. Don't know what you ask.

**Comment by textbrowser** [comment] 2024-10-15 17:09
You place mouse cursor over the single line and press Enter then have two lines and then Save.

**Comment by textbrowser** [comment] 2024-10-15 17:12
Or you let the imported data be what it is and the hyper will function for that single book unless others have got milk like you now have. Will not work for got and milk as singular in that particular instance because got milk is one and not two. Want two? Press the Enter.

**Comment by meteos77** [comment] 2024-10-15 17:13
I couldn't find the discussion, but you explained something else to me. I'm going to look in depth for old exchanges.

**Comment by textbrowser** [comment] 2024-10-15 17:13
Nah, I would remember that. There be a tool tip too for pressing alt and focusing and clicking.

**Comment by textbrowser** [comment] 2024-10-15 17:14
BQ creates hypers for each lined item. So if "got milk" and "don't got milk" are two lines in said field, you got two hypers. Lines are hypers and single line is one long hyper irrespective of spaces.

**Comment by meteos77** [comment] 2024-10-15 17:15
In any case, your solution is not feasible for 600 imported documents.

**Comment by textbrowser** [comment] 2024-10-15 17:15
Problem is that your original items appear as two hypers in book item and single item in table column. So you export and got one item and then import and got one item but you want two hypers.

**Comment by textbrowser** [comment] 2024-10-15 17:17
> In any case, your solution is not feasible for 600 imported documents.

Again, you either get 25 items in table with newlines and big row or you get wide columns. And this is for hypers and exports. So you want ugly tall column and can't see anything else just so you can get hypers. Makes no sense so this has to break other people's brains.

**Comment by meteos77** [comment] 2024-10-15 17:19
I don't think you've understood me : hypers are not accessible via the board?

**Comment by textbrowser** [comment] 2024-10-15 17:19
Libre probably does not work with values spanning multiple rows. And so we need special values like \\n for lines and treat lines maybe special in export. But why you export from BQ and them import into BQ? Nonsense. Copy the database.

**Comment by textbrowser** [comment] 2024-10-15 17:19
What board? What is board? Chess? Mahjong?

**Comment by textbrowser** [comment] 2024-10-15 17:22
Will try to interpret \n (newlines) in import for keywords. But newlines which are visible not lines spanning multiple rows.

**Comment by textbrowser** [comment] 2024-10-15 17:23
Where you get data from if you have 600?

**Comment by meteos77** [comment] 2024-10-15 17:23
Let's not talk about exports any more - that's part of the problem.

When the 600 documents arrive, we want to retrieve the information from the unimarc records transformed into csv.
the information concerning the subject of the document is often multi-word, and therefore multi-hypertext.

**Comment by textbrowser** [comment] 2024-10-15 17:23
Explain data origin.

**Comment by textbrowser** [comment] 2024-10-15 17:25
"hello you broken" is multiple words. How you want BQ to know that? "I know an atom." is a structured sentence and you want hypers or one hyper? How BQ supposed to know? Magic from Mahjong!

**Comment by textbrowser** [comment] 2024-10-15 17:26
In download from 39.5 or SRU, keywords or categories are separated properly so BQ knows. It thinks and concludes with knowledge. In import, how it knows you want 3 millions hypers?

**Comment by textbrowser** [comment] 2024-10-15 17:28
Commas? Nope. Any character it doesn't know. You need special sequence but then that breaks someone too unless sequence tells BQ that this field includes replacements for hypers or something else.

**Comment by meteos77** [comment] 2024-10-15 17:29
It seems to me that you told me the solution... I'm looking for it...

**Comment by textbrowser** [comment] 2024-10-15 17:29
Tell us your categories in CSV which you know that they need separation and which character and we need to introduce separation anxiety into BQ. Like, BQ replace this with that. ';' -> \n

**Comment by meteos77** [comment] 2024-10-15 17:32
Can we have a double character, for example “;;”

**Comment by textbrowser** [comment] 2024-10-15 17:37
No.

**Comment by textbrowser** [comment] 2024-10-15 17:37
Your sequence is someone's reality.

**Comment by textbrowser** [comment] 2024-10-15 17:38
Need column and rows and some defaults which free us from doing this again for hypers. I know I could solve this like in a few seconds from data inspection and some scripties and parties but that's another story for another time.

**Comment by textbrowser** [comment] 2024-10-15 17:39
So now more big project.

**Comment by meteos77** [comment] 2024-10-15 17:42
Good project then thanks for all the explanations.

**Comment by textbrowser** [comment] 2024-10-15 18:34
We love virtual real people.

**Comment by meteos77** [comment] 2024-10-15 18:46
> We understood before you posted and the request is kind of, maybe not so kind, silly because hypers are not a commodity. And your data is not kind of but is broken because it has special characters. What would be difficult but fancy would be to import that and then have a big download of SRU for 600 items but not easy to do with single pair of hands. So we have all the solutions all ready but they ain't implemented. Implementation is like the people going to build the bridge. Free bridge and no one pays them. Like prison labor.

That would be great :-)


I've made a bit of a script based on yours for uploading images
[Telechargement_BnF-ark_resume_physique.sh.tar.gz](https://github.com/user-attachments/files/17383163/Telechargement_BnF-ark_resume_physique.sh.tar.gz)

**Comment by meteos77** [comment] 2024-10-18 09:06
> Tell us your categories in CSV which you know that they need separation and which character and we need to introduce separation anxiety into BQ. Like, BQ replace this with that. ';' -> \n


Why not use the same thing as the html representation.
if BQ encounters ` <br>` , it's already a line break in the representation.

he could also apply this to links : a` <br>`  indicates that each line becomes a hyperlink.

1 - If several words but no ` <br>`  between the words the link is on the expression :
Horses Animals -> 1 link: “Animal Horses"

2 - If the words are separated by` <br>` it becomes 2 hypertext keywords:
Horses ` <br>`  Animals -> 2 links: “Horses” and “Animals"

**Comment by textbrowser** [comment] 2024-10-18 14:53
Why don't I do this? This is answering yourself. I know how to solve problems but I have to solve problems for people because they don't or don't want to. It doesn't matter how I want to do it. I need to do something that allows a person to do it for themselves and in which the solution solves a particular problem with as much open-ness as I am able to. Open-ness, maybe flexibility. It's like if you suggest how I solve then you can already solve the problem for yourself.

**Comment by meteos77** [comment] 2024-10-18 15:22
You can already solve it yourself ?

Interesting, but from your point of view the solution is easy ... but from my point of view ... 
That's why I'm asking a question on github :-)

**Comment by meteos77** [comment] 2024-10-18 15:41
https://github.com/textbrowser/biblioteq/issues/163#issuecomment-1004876587 ... Still hard to find since January 2022.

Would have deserved to appear in the documentation.

I've carried out an initial test and it seems conclusive.

Thanks for your help in 2022 :-)

**Comment by textbrowser** [comment] 2024-11-11 00:33
As example suggests, include <br> tags in desired fields. Closing.

**Closed by textbrowser** 2024-11-11 00:33 UTC
Labels: Much-Content, Not-An-Error
