### ISSUE TITLE
Version 2020.07.04 issues encountered

### ISSUE THREAD

**Issue by jerzyPL** [textbrowser/biblioteq#72] opened 2020-07-09 18:57 UTC
Good evening,
the issues I noticed regarding the July 4, 2020 release.

### **1. Database Enumerations Browser:**
- new values ​​can be entered in the "Book Binding Types", "Languages" and "Monetary Units" fields, but these values ​​(after entering them in the appropriate fields and confirming) disappear after pressing the "Save Changes" button.
Of course, they are then available in the "Create Book Entry"/"Modify Book Entry" windows, but only those last saved (e.g. after entering "Hardcover", "Polish" and "Polish Zloty" in "Database Enumerations Types" and confirming, then, in the "Create Book Entry"/"Modify Book Entry" windows, in the "Book Binding Types" and "Languages" fields, I have the "UNKNOWN" values, and only in "Monetary Units" I have "Polish Zloty", and so in any other configuration).
- the only values ​​in "Database Enumerations Browser" that do not disappear are "Locations" (Type/Location).
### **2. Main Window (Table Mode):**
- the "Select Viewable Columns" button, after pressing it, contains two different sets of columns:
**1)** Title, **ID Number**, Publisher, Publication Date, Categories, Language, Price, Monetary Units, Quantity, **Location**, Availability, Total Reserved, Accession Number, **Type**.
**2)** Title, **Authors**, Publisher, Publication Date, **Place of Publication**, **Edition**, Categories, Language, **ISBN-10**, Price, Monetary Units, Quantity, **Book Binding Type**, **ISBN-13**, **LC Control Number**, **Call Number**, **Dewey Class Number**, Availability, Total Reserved, **Originality**, **Condition**, Accession Number.
This second set only appears when I add another book, but it disappears when I disconnect and reconnect to the database, and so I have the first set instead of the second.
In my opinion, the second set is more rational.
### **3. Other Options:**
Regardless of checking or unchecking the "Show Table Tools Tips" option, the tips are displayed, but only for books without a front/back cover picture.
After adding front/back cover pictures, a white screen appears and then such a picture (bug?) for half a second.
![screenshot](https://user-images.githubusercontent.com/66644295/87078615-37903e80-c225-11ea-9aa9-287ca8eafeea.jpg)
### **4. Accession Number:**
Assigns a sequential number to all copies, even if the previous copy has been deleted (e.g. because of wrong ISBN).

**Comment by textbrowser** [comment] 2020-07-09 23:04
SQLite database?

**Comment by textbrowser** [comment] 2020-07-09 23:09
1. Yes, correct. Reproduced.

**Comment by textbrowser** [comment] 2020-07-09 23:23
1. Refresh corrected. Also added a shortcut to the refresh button: Control + R.

**Comment by jerzyPL** [comment] 2020-07-09 23:26
Yes, SQLite database. I tried to fix it using SQLiteStudio (3.2.1) and it works (more or less), but I don't think that it's correct way.

**Comment by textbrowser** [comment] 2020-07-09 23:27
The first issue is a problem and has been corrected. Targeting for a release on Saturday.

**Comment by textbrowser** [comment] 2020-07-09 23:29
2. The available columns are based on the current category. ISBNs are not applicable to an All category.

**Comment by textbrowser** [comment] 2020-07-09 23:36
2. The available columns are prepared whenever the category changed. If the option Populate View on Item Creation is set, the table is populate and the category is changed to reflect the type of the most recently-added item. Disconnecting from the database and reconnecting will set the category to the last user-set category.

**Comment by jerzyPL** [comment] 2020-07-09 23:39
Ad 2. You are right: the "Authors" & the other fields appear after choosing "View" => "Category" =>"Books". Thank you.

**Comment by textbrowser** [comment] 2020-07-09 23:42
4. Yes, sequences must be incremented uniquely. Imagine the following scenario: create two new books. If the sequence is not incremented uniquely, both books would have an accession number of 2 (for example).

**Comment by textbrowser** [comment] 2020-07-09 23:45
4. Sequences usually increment and are never decremented nor removed. Remember, the sequence value is a suggestion. It can be manually modified. Also, BQ supports PostgreSQL. As such, multiple people may be adding books. Correctness must be preserved.

**Comment by textbrowser** [comment] 2020-07-09 23:49
2. Was caused by the removal of std::nothrow. Out-of-memory exceptions are generally difficult to resolve correctly.

**Comment by jerzyPL** [comment] 2020-07-10 00:00
Understood, OK.
BTW: Is it possible to change/adjust the order of the columns? My point is to have the "Accession Number" on the front, even before the "Title" and "Authors". And what is the column order key, probably not alphabetic?

**Comment by textbrowser** [comment] 2020-07-10 00:04
Order of columns may be changed temporarily via drag-and-drop of column titles. Orders are not retained over category changes and sessions.

**Comment by textbrowser** [comment] 2020-07-10 00:19
3. Remember to reload the table after the Show Table Tool Tips is modified. There is a tool tip reminder attached to the option. Otherwise, corrected. Problem caused by the capturing of binary data during the creation of tool tips.

**Comment by textbrowser** [comment] 2020-07-10 00:27
Anything else?

**Comment by jerzyPL** [comment] 2020-07-10 00:42
I think I will give up with the "Show Table Tools Tips" feature...
So on Saturday we are expecting a new release?
Thanks for now. Good night.

**Comment by textbrowser** [comment] 2020-07-10 00:48
Give up? It's been corrected as there is a problem caused by binary data.

**Comment by textbrowser** [comment] 2020-07-10 00:50
3. Tool tips on the main table are generated before the table is populated, if enabled. Toggling the option will not disable / enable tool tips in real-time.

**Comment by textbrowser** [comment] 2020-07-10 17:28
Thank you for the reporting!

**Comment by textbrowser** [comment] 2020-07-11 17:27
Most of the packages have been uploaded. The Windows release is ready. Closing. Please open a new ticket if you discover other problems.

**Closed by textbrowser** 2020-07-11 17:27 UTC
