### ISSUE TITLE
Can't install on Ubuntu 18.04

### ISSUE THREAD

**Issue by leemour** [textbrowser/biblioteq#47] opened 2019-03-12 11:16 UTC
When I install `BiblioteQ-2018.12.12_amd64.deb` file from sourceforge, it reaches 100% installation but then nothing happens and Install button is active, I can click it endlessly with same effect. I have installed Qt5 and Yaz. Anything else I can do?

And why does it show license as Proprietary btw?

**Comment by textbrowser** [comment] 2019-03-12 12:05
If we look at https://github.com/textbrowser/biblioteq/blob/master/DEBIAN/control, we see that a license isn't mentioned. Perhaps that's the cause. I will see if a license section is available. Or, you may.

After the installation, is BQ available in some menu? Ubuntu has many menus. How about in /usr/local/biblioteq?

The Debian control file was tested with Debian. I don't recall the version. I attempted the installation just now with Kubuntu 18.10 and it failed because of libyaz4, a library that is not available in Kubuntu 18.10. I will see if a virtual reference is better.

**Comment by textbrowser** [comment] 2019-03-12 12:23
License section doesn't exist: https://www.debian.org/doc/debian-policy/ch-controlfields.html.

**Comment by textbrowser** [comment] 2019-03-12 12:31
The source has been modified to include the Russian translation.

**Comment by leemour** [comment] 2019-03-12 12:31
> After the installation, is BQ available in some menu? Ubuntu has many menus. How about in /usr/local/biblioteq?
I think I should've done it from terminal first. Here's what I get:
```
Preparing to unpack BiblioteQ-2018.12.12_amd64.deb ...
Unpacking biblioteq (2018.12.12) ...
dpkg: dependency problems prevent configuration of biblioteq:
 biblioteq depends on libyaz4 (>= 4.0); however:
  Package libyaz4 is not installed.

dpkg: error processing package biblioteq (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.23-1ubuntu3.18.04.2) ...
Processing triggers for gnome-menus (3.13.3-11ubuntu1.1) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Errors were encountered while processing:
 biblioteq
```
I have libyaz5 installed and there's no package libyaz4 available. What should I do?

**Comment by textbrowser** [comment] 2019-03-12 12:31
![screenshot](https://user-images.githubusercontent.com/10701156/54200217-3fa96400-44a1-11e9-832a-911a4588a53e.png)

**Comment by textbrowser** [comment] 2019-03-12 12:34
Right, yaz4 is deprecated. Simple, compile it from source! Or wait until the next release.

**Comment by textbrowser** [comment] 2019-03-12 12:35
Let me see if a new Debian package will work with the virtual libyaz-dev package.

**Comment by leemour** [comment] 2019-03-12 12:35
@textbrowser sorry for silly question but how do I compile it from source?:)

**Comment by textbrowser** [comment] 2019-03-12 12:39
You'll need a bunch of packages. I don't have them listed. My process is:
a) install Qt 4 or 5 if 4 is not available
b) git clone https://github.com/textbrowser/biblioteq biblioteq.d
c) cd biblioteq.d
d) qmake -o Makefile biblioteq.pro
e) make -j 5
f) sudo aptitude install ... until all dependencies (d) are satisfied

**Comment by leemour** [comment] 2019-03-12 12:40
concerning the license I think we need a `copyright` file https://www.debian.org/doc/manuals/maint-guide/dreq.en.html#copyright

**Comment by textbrowser** [comment] 2019-03-12 12:43
Ya, that's a new file? More files!

**Comment by textbrowser** [comment] 2019-03-12 12:45
OK, installation failed. The virtual package doesn't exist. A virtual package libyaz-dev does but that won't satisfy the installation because the package is intended for builders. Or will it?

**Comment by leemour** [comment] 2019-03-12 12:45
When using `qmake` I get
```
Info: creating stash file /home/leemour/Books/biblioteq/.qmake.stash
Info: creating cache file /home/leemour/Books/biblioteq/.qmake.cache
Project MESSAGE: The directory /usr/include/poppler/cpp does not exist. Poppler version information will not be available.
```
Is this ok?

**Comment by textbrowser** [comment] 2019-03-12 12:46
Sure. "Poppler version information will not be available." BQ's About includes some information pertaining to your platform, etc.

**Comment by leemour** [comment] 2019-03-12 12:47
> f) sudo aptitude install ... until all dependencies (d) are satisfied
can you please clarify what should I install?

**Comment by textbrowser** [comment] 2019-03-12 12:48
I need an example failure.

**Comment by textbrowser** [comment] 2019-03-12 12:52
Include files (because of missing packages) and/or linking (because of missing libraries) failures during the **make** phase.

**Comment by leemour** [comment] 2019-03-12 12:57
Well I ran all commands a-e and don't see any errors (so I guess make worked). What do I do next? running `biblioteq` does nothing

**Comment by textbrowser** [comment] 2019-03-12 12:59
Try **./BiblioteQ**.

**Comment by textbrowser** [comment] 2019-03-12 13:04
Working? No? Something else? Maybe? You should be able to create an SQLite database. For PQ, that's another matter. I do not have enough space here to discuss.

**Comment by leemour** [comment] 2019-03-12 13:06
Awesome! It works! Thanks! Now I guess I need to symlink that to a folder in PATH?

**Comment by leemour** [comment] 2019-03-12 13:07
PQ would be awesome, but not needed at this point. Maybe I'll torture you later:)

**Comment by textbrowser** [comment] 2019-03-12 13:07
A successful installation installs BQ in /usr/local/biblioteq. See Documentation/README.DEBIAN.

**Comment by textbrowser** [comment] 2019-03-12 13:09
So I don't provide PQ guidance because that's the administrator's task. It's a learning experience.

**Comment by leemour** [comment] 2019-03-12 13:12
Ok I understand, one last thing, how do I use the lastest on Windows? Since the Librarian I'm helping will be using Windows. Shall I wait for the next release from you?

**Comment by textbrowser** [comment] 2019-03-12 13:14
Yes or you can build it there from source too. It's much easier to build on W32. Deploying it there, however, is more work because of the many DLLs. Remember also that the version will change.

**Comment by textbrowser** [comment] 2019-03-12 13:17
OK, good luck and thank you for the new translation.

**Comment by textbrowser** [comment] 2019-03-12 13:19
Oh, if this is a network installation, PQ is best. Don't use SQLite. See Documentation/Administrator Guide.pdf and SQL/postgresql_create_schema.sql.

**Comment by leemour** [comment] 2019-03-12 13:20
Sorry to ask again but can you point me to a guide on how to build it for Windows?
I guess we'll have it on one PC for now and later I'd probably go for the PQ guide:)

**Comment by textbrowser** [comment] 2019-03-12 13:34
No, one doesn't exist. Why?

**Comment by textbrowser** [comment] 2019-03-12 13:36
Just kidding. No, not about one not existing.

a) Download the W32 online installer from http://download.qt.io/official_releases/online_installers/
b) Capture the BQ source (GitHub has a W32 interface somewhere)
c) I use the W32 terminal (one is prepared by the Qt installer), or much luck with Qt's Creator
d) qmake -o Makefile biblioteq.win.pro (terminal)
e) make

See from there.

**Comment by textbrowser** [comment] 2019-03-12 14:17
Closing!

**Closed by textbrowser** 2019-03-12 14:17 UTC
