### ISSUE TITLE
Installation help.

### ISSUE THREAD

**Issue by MossyQuill** [textbrowser/biblioteq#368] opened 2024-05-22 02:57 UTC
Apologies if this is an obvious mistake/issue (most likely user error, as I'm new to Qt and C++) but I'm having an issue with installing BiblioteQ for Windows. 

I have Qt installed and extracted the biblioteq directory to desktop. The next step is probably where the mistake is. From the Qt Creator "Welcome" page, I selected Open Project, then navigated to the directory and chose the biblioteq.win file. This imported the project to Qt. I opened the project and clicked on bioblioteq.win.pro and ran it to build the program file, which threw an error towards the end. I tried this for the two most recent versions of BiblioteQ, and got different errors preventing the file from being built for each.

On the most recent version (30-04-2024) it was 'Error 1' for an unrecognized sequence (" -/ ") in the command line, and for the previous version (25-03-2024) it was an error 1 resulting from inability to find ' -lyaz5.' The following is the exact error (from the March version): 
C:/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lyaz5
collect2.exe: error: ld returned 1 exit status
mingw32-make[1]: *** [Makefile.Release:313: release/BiblioteQ.exe] Error 1

with the elaboration: 
Error while building/deploying project biblioteq.win (kit: Desktop Qt 6.7.1 MinGW 64-bit)
When executing step "Make"

Any help is appreciated!

**Comment by textbrowser** [comment] 2024-05-22 03:38
[Windows-Installation.pdf](https://github.com/textbrowser/biblioteq/files/15397682/Windows-Installation.pdf)

**Comment by textbrowser** [comment] 2024-05-22 03:46
I do not use Qt Creator for Windows. The pasted PDF is in the Documentation directory so that's there for you to read. Many questions about compilations that I cannot answer all and so I create many documents which are not read and then create release files and make install targets. Best that you resolve or wait for another release. Cannot make it any more simple than mingw32-make and mingw32-make install. I use the process well.

**Comment by MossyQuill** [comment] 2024-05-22 19:17
> I do not use Qt Creator for Windows. The pasted PDF is in the Documentation directory so that's there for you to read. Many questions about compilations that I cannot answer all and so I create many documents which are not read and then create release files and make install targets. Best that you resolve or wait for another release. Cannot make it any more simple than mingw32-make and mingw32-make install. I use the process well.

Thank you, I did already read your Windows install instructions. It's understandable if you can't help because you don't use Windows, but it's honestly quite rude to accuse me of not reading or trying to solve this issue before posting and then labeling my question as "duplicate." If it genuinely is a duplicate of a previous post where there is better explanation of Windows installation, then please point me to it and I'll gladly read it. 

As I said in my post, this is more likely an issue in my process of how I'm trying to install the program, as I'm not super familiar with Qt or C++. I made no accusations towards you or the quality of your program, I'm simply looking for help. 

Your instructions may seem simple to you, but they are not clear for people who are not full time programmers/devs. In the same way that it would be confusing for you if I told you to "just calibrate the XRF spectrometer for obsidian analysis" it is also confusing to me when you say "mingw32-make install." I'm doing my best to learn so I can properly install your program in good faith, and I'd appreciate it if you could at least be polite in response--even if you're only letting me know that you're unable to help (which is fine if that's the case, just be polite when saying so).

**Comment by textbrowser** [comment] 2024-05-22 19:45
I be not rude. I help you with document. Like, here, try this. Read it and understand it and follow it. I follow it and another person follow it. So two people follow it and two people understand it. You need not be a full-time or part-time or any-time anything. The document has instructions written from an altruistic mind. Like, this. If I am confused, how do I write about this so others more or less confused reproduce? It is all about reproducing a process so it understood. And yes, duplicate because it has been asked in some variation.

**Comment by textbrowser** [comment] 2024-05-22 19:51
I be familiar with calibration and spectrometer so I be not as confused if you approach me with such words. I would wonder if there is a document and then follow the document and comment on it if I find it inadequate. See? I paste document for you to read and step-wise it and comment if it does not aid you in a proper conclusion. Then you comment and then I edit or you edit and a better document. Simple and productive. But I can be rude by dismissing you or closing your comment or ignoring the request well because many request things and my time is not your time and your time is not my time; but we come to an agreement to satisfy your need. Then we happier than before. OK, so try following the document and if questions, paste or type here and I address those and then amend document.

**Comment by textbrowser** [comment] 2024-05-22 19:58
I have to move soil and put caps on gardens soon so will return to the document with elaborate words to lessen the confusion. So in Windows there are DOS terminals and Qt has provided, goodness for that, a copy of the DOS terminal or maybe not a copy but a derivative, in which the respective Qt environment is present when the terminal is launched. As I do not know which Windows there is; maybe 9 or 10 or 11 or Vista or whatever, I present it generically; do this in Windows because the Windows person will know how to.

Anyway, Qt DOS Terminal; I would search for it.

Then you change the directory in the prompt via cd to the location of the biblioteq.win.pro file. More clarity will be included in the document.

> qmake -o Makefile biblioteq.win.pro
> mingw32-make
> mingw32-make install

Then you can double-the-click on the BiblioteQ.exe file in the release folder and all well. But sure more words and perhaps some images. But some of this should be like not a doctor's procedure or a satellite operator. It need not be perfect because the process is quite simple. Is not an avionic process. Bye now.

**Comment by textbrowser** [comment] 2024-05-23 01:21
An amended document is present and excludes Qt Creator because documenting that would be a project.

**Comment by textbrowser** [comment] 2024-05-23 03:01
https://github.com/textbrowser/biblioteq/tree/master/Documentation/Windows-Installation.d

**Comment by textbrowser** [comment] 2024-05-23 16:11
Silent person. Closing.

**Closed by textbrowser** 2024-05-23 16:11 UTC
Labels: Duplicate

**Comment by MossyQuill** [comment] 2024-05-24 22:22
Sorry for not responding sooner, I haven't had time to reply.

> https://github.com/textbrowser/biblioteq/tree/master/Documentation/Windows-Installation.d

This was incredibly helpful, thank you! I think the best way to update your instructions document for future users would be to edit step 2 ("Open a Qt DOS terminal.") to instead say: 

2. Open the DOS terminal from the installed Qt folder. It will be titled "Qt [version] (MinGW [version] 64-bit)."

Following your instructions from the first section of the guide resulted in the installation of a folder titled "Qt" which contains the DOS terminal, Qt creator, linguist, designer, etc. which looks like this in quick file access:

![image](https://github.com/textbrowser/biblioteq/assets/170482376/aa4d69c1-db27-47ba-b9b5-1f7964ea13df)


Installing Qt also automatically opened both Creator and Designer, so that's why I was trying to apply your instructions in Creator, which also has a DOS terminal but does not accept any of the commands you said to use. Of course, having non-working commands in the wrong DOS terminal led to a bit of confusion lol. 

Anyway, thank you for your help and the screenshots from your emulator, it is greatly appreciated.

**Comment by textbrowser** [comment] 2024-05-24 22:32
> Sorry for not responding sooner, I haven't had time to reply.
> 
> > https://github.com/textbrowser/biblioteq/tree/master/Documentation/Windows-Installation.d
> 
> This was incredibly helpful, thank you! I think the best way to update your instructions document for future users would be to edit step 2 ("Open a Qt DOS terminal.") to instead say:
> 
>     2. Open the DOS terminal from the installed Qt folder. It will be titled "Qt [version] (MinGW [version] 64-bit)."
> 
> 
> Following your instructions from the first section of the guide resulted in the installation of a folder titled "Qt" which contains the DOS terminal, Qt creator, linguist, designer, etc. which looks like this in quick file access:
> 
> ![image](https://private-user-images.githubusercontent.com/170482376/333747438-aa4d69c1-db27-47ba-b9b5-1f7964ea13df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1ODk5ODgsIm5iZiI6MTcxNjU4OTY4OCwicGF0aCI6Ii8xNzA0ODIzNzYvMzMzNzQ3NDM4LWFhNGQ2OWMxLWRiMjctNDdiYS1iOWI1LTFmNzk2NGVhMTNkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQyMjI4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzNkMWFkZWViYTI4NzRkNTkyNjViNDY0NjI4MDRjZWFhOGVkZjYwOWVjZmMzYmMzMmZmZDJiMjk2MDllNDIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d4pCnexNKsrQrFSJQECiJ222dKPnUqMRTCVa2wBpkpE)
> 
> Installing Qt also automatically opened both Creator and Designer, so that's why I was trying to apply your instructions in Creator, which also has a DOS terminal but does not accept any of the commands you said to use. Of course, having non-working commands in the wrong DOS terminal led to a bit of confusion lol.
> 
> Anyway, thank you for your help and the screenshots from your emulator, it is greatly appreciated.

I ambiguous purposely on Windows because there are ambiguous versions and if specifics then those specifics will be idolized and people tend to become upset if instructions, which are free and courteous, are not exactly exact. There are assumptions which documentation. Like, opening a Qt DOS terminal is something one can query on their platform because Windows 11 is not 10 nor 9 nor XP. There are hints.
