### ISSUE TITLE
Small problems detected.

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#226] opened 2022-08-22 18:38 UTC
price field
- the locale '.' and ',' as decimal separator on the field "price" has a defect
- in english the decimal separator is a point, in most european countries it is the comma.
    - import csv takes only the .
    - the display in book is a ,
    - the display in the table is a .

"condition field
- the sorting order (alphabetical) for the field "condition" is not optimal because in a language other than English, the translation changes and thus no more coherence
suggestion : add 1, 2 3 in the label (sort from the best condition to the most degraded so all languages will be in the same order)

it also allows to charge a document if the borrower returns a book with 3 levels of difference between the condition at the time of the loan and the condition at the time of return

**Comment by meteos77** [comment] 2022-08-22 18:46
[importationBQ-Price-Decimal-TEST.csv.tar.gz](https://github.com/textbrowser/biblioteq/files/9396798/importationBQ-Price-Decimal-TEST.csv.tar.gz)

**Comment by textbrowser** [comment] 2022-08-23 00:48
I committed a change for the table price.

**Comment by textbrowser** [comment] 2022-08-23 15:15
Condition: the values in the UI are translatable.

**Comment by meteos77** [comment] 2022-08-23 15:27
![condition-order](https://user-images.githubusercontent.com/56431039/186198345-7dc2a945-45d3-4777-a0d3-acc1e70ab31b.png)

the list in English has a logic (alphabetical order)
the list in French has no logic

**Comment by textbrowser** [comment] 2022-08-23 15:30
Are you requesting that the values in the combination box be ordered? Or to change the sort logic of the table?

**Comment by textbrowser** [comment] 2022-08-25 12:26
Price locale import: the price must be enclosed by double quotes. This allows the regular expression to retain the commas in a quoted field. Similar to other fields. The export from BQ does enclose fields by double quotes if the values in those fields contain commas.

**Comment by textbrowser** [comment] 2022-08-25 12:37
Here's an image of a translated Condition entry in the main table. The translation occurs before the book entry is saved and therefore the text in the SQLite database is the translated text.

sqlite> select condition from book;
Comme neuf
As New
As New
As New
As New
As New
As New
As New
As New

![Screenshot_20220825_083525](https://user-images.githubusercontent.com/10701156/186666462-9861e438-9a3e-4f7f-a24a-d0c13f05fc78.png)

**Comment by meteos77** [comment] 2022-08-25 18:52
*condition field :  sorry I did the translation backwards EN-> FR and I was not clear.

when creating a book, you can specify its physical status (fields: condition in the database) by the pop-up

the pop-up proposed by BQ if the interface is configured in English, the pop-up list is presented in alphabetical order.

in another language like French, the beginning of the words changes and so the alphabetical list in English, becomes a list without particular sorting order in French. this forces the French user to browse the whole list to be able to find the chosen state for the document

in English for the state "poor" you go directly to the bottom of the alphabetical list because it starts with "P". 

in French for the state "Bon" you expect to find it in 1st position at the top of the list if sorted alphabetically while it arrives in 7th position (Good in English)

my suggestion was to sort them in order of quality by adding a number in front of it, because in English or French, we will always use Arabic numbers :-)

**Comment by meteos77** [comment] 2022-08-25 18:54
for the import with price I had tested with and without double quotes but it did not change anything.

I will test again as soon as possible and keep you informed

**Comment by textbrowser** [comment] 2022-08-25 19:44
The expectation that the import tool should consider locale-specific data is quite high (almost absurd). A double is represented by a sequence of decimal digits and a single separator (the dot). The value 5.55 is locale-agnostic while the value 5,55 is not. BQ cannot detect the locale from a CSV file. Price values are recorded as double (real) values, not strings. Displayed values versus representations are different.

**Comment by textbrowser** [comment] 2022-08-25 22:49
Condition values are now sorted. :) Please test. I'd like to bundle the releases soon.

**Comment by meteos77** [comment] 2022-08-26 07:02
sorry the earth is not converted to the us system :-)
it's the same thing with unimarc and marc21 but more universal

the dot "." is for Anglo-Saxons
the comma "," is for Europeans

[Decimal separator](https://en.wikipedia.org/wiki/Decimal_separator)

BiblioteQ in Europe should recognize the comma because the common use of the dot is the separator of thousands.
All our tools (libreoffice, calculator ... put a comma when you type the point on the numeric keyboard)

in the import tool a simple transformation in the price field from comma to point should be ok for BQ ?

**Comment by meteos77** [comment] 2022-08-26 07:08
$> env LC_NUMERIC=en_US.UTF8 printf '%f\n' 1233.14
1233.140000
$> env LC_NUMERIC=en_US.UTF8 printf '%f\n' 1233.14
1233,140000

**Comment by meteos77** [comment] 2022-08-26 07:12
The book condition part is ok,  thanks for the evolution

**Comment by meteos77** [comment] 2022-08-26 09:42
remark: 
in the interface of the books, I can not put the price with a decimal number by the numeric keyboard the key ".suppr" is not taken into account.
I have to use the ",?" key to put the comma and continue the input on the cents
![clavier_fr_FR](https://user-images.githubusercontent.com/56431039/186876530-a1a63def-4239-4f9e-922d-0d4cd895563f.jpg)

**Comment by meteos77** [comment] 2022-08-26 09:58
as you like to laugh a little video : https://www.youtube.com/watch?v=JeiihmJ1VEk

**Comment by textbrowser** [comment] 2022-08-26 11:22
I thought about your request during a dream. Yup, BQ can translate the price from a locale-specific string to a double (real).

**Comment by textbrowser** [comment] 2022-08-26 11:28
OK, uploaded!

**Comment by meteos77** [comment] 2022-08-26 11:39
super ! it works well for me, the import is OK
on the other hand I discovered a lot of small inconsistencies between price and monetary units

do you want to see them before the release of the package or do you prefer to focus on this one ?

you make beautiful dreams :-)  for me it's more like :  [unreal](https://www.youtube.com/watch?v=z_YtgBtLNeg)

**Comment by textbrowser** [comment] 2022-08-26 11:42
> sorry the earth is not converted to the us system :-) it's the same thing with unimarc and marc21 but more universal
> 
> the dot "." is for Anglo-Saxons the comma "," is for Europeans
> 
> [Decimal separator](https://en.wikipedia.org/wiki/Decimal_separator)
> 
> BiblioteQ in Europe should recognize the comma because the common use of the dot is the separator of thousands. All our tools (libreoffice, calculator ... put a comma when you type the point on the numeric keyboard)
> 
> in the import tool a simple transformation in the price field from comma to point should be ok for BQ ?

The metric system is the best. A comma replacing the decimal point... not so much. And in French, 100,000.00 is not 100,000,00. Right?

**Comment by textbrowser** [comment] 2022-08-26 11:43
How did you test it so quickly?

**Comment by meteos77** [comment] 2022-08-26 11:44
in french 100.000.00 does not exist
10.000.000 or 10.000.000,00

**Comment by meteos77** [comment] 2022-08-26 11:45
git pull
make -j8
nouvelle base de données
import csv

**Comment by meteos77** [comment] 2022-08-26 11:50
principle export = import are not respected
if export csv, the field price contains the currency symbol €.

**Comment by meteos77** [comment] 2022-08-26 11:51
if monetary units are different from €, the display in the table in the price column is always €?

**Comment by meteos77** [comment] 2022-08-26 11:53
I can provide you with the French translation, the translatable texts will not change anymore?

**Comment by textbrowser** [comment] 2022-08-26 12:05
> if monetary units are different from €, the display in the table in the price column is always €?

No. The price is represented by a NUMERIC(10, 2) value.

https://github.com/textbrowser/biblioteq/blob/master/SQL/postgresql_create_schema.sql

**Comment by meteos77** [comment] 2022-08-26 12:12
sorry translation (2 word in french , 1 word in english)
table (sql) = table (in french table)
table view = table (in frenc tableau)

**Comment by textbrowser** [comment] 2022-08-26 12:17
> I can provide you with the French translation, the translatable texts will not change anymore?

Sure. If I have additional changes, I'll let you know.

Release notes and visible text remain for you to translate.

**Comment by meteos77** [comment] 2022-08-26 12:33
As usual, Europeans have a problem :-)   before 2002, each european country had its own monney

in France, a document before 2002 was in "Francs" currency
in Germany, a document dated before 2002 was in "Mark" currency
in Spain a document before 2002 was in "Peseta" currency
...
so BQ can't automatically put the € currency unit symbol because if a book is from before 2002, it's anything but €

the monetary units field allows you to specify the currency

that said, I think it's great to have the money symbol in the UI table!

**Comment by meteos77** [comment] 2022-08-26 12:36
for me the import can not contain a currency symbol otherwise the import does not take the amount
[importationBQ-Price-Decimal-TEST.csv.tar.gz](https://github.com/textbrowser/biblioteq/files/9433209/importationBQ-Price-Decimal-TEST.csv.tar.gz)
example 3 and 4

**Comment by textbrowser** [comment] 2022-08-26 12:42
Let me see.

**Comment by meteos77** [comment] 2022-08-26 12:57
enumeration database pop-up (see condition field pop-up (alphabetical sorting))
![database-enumeration_alphabetic_order](https://user-images.githubusercontent.com/56431039/186908446-e5a16f91-c008-4e70-bc42-0771a07b3ecf.jpg)

we have the same "problem" with the sorting on the enumeration database pop-up.
the order in french doesn't correspond to anything.

**Comment by textbrowser** [comment] 2022-08-26 14:18
Yup. This is relevant everywhere where fixed lists are located. There is nothing automatic that is available. All of the logic must be developed. It's expensive software.

**Comment by meteos77** [comment] 2022-08-26 14:26
I'm doing my (French) user feedback :-), on this point, the previous version we didn't have this pop-up option.
As the title of the ticket says, these are "small problems", we can use the software as it is.
Your precious time is for me more useful in the new features.

**Comment by meteos77** [comment] 2022-08-26 14:28
ask Qt something like "locales.sort.popup" :-)

**Comment by textbrowser** [comment] 2022-08-26 14:34
It's a frustration instead of a time-sensitive problem. I see it as a problem that some people will face if they believe that a list should be sorted. I sort it in English because it's a preference. These details are very expensive because nothing is automatic. For traditional tables and lists, Qt provides a means of sorting entries so one does not have to provide new instructions.

**Comment by textbrowser** [comment] 2022-08-26 14:59
OK, the currency symbol must be removed from the string before the locale-specific value is converted into a double. QLocale does not remove the currency symbol automatically. Test now.

**Comment by textbrowser** [comment] 2022-08-26 15:36
> enumeration database pop-up (see condition field pop-up (alphabetical sorting)) ![database-enumeration_alphabetic_order](https://user-images.githubusercontent.com/56431039/186908446-e5a16f91-c008-4e70-bc42-0771a07b3ecf.jpg)
> 
> we have the same "problem" with the sorting on the enumeration database pop-up. the order in french doesn't correspond to anything.

This is more problematic because sorting the entries in the combination box requires that the widget portions also be sorted. That is, the location of the widgets must be dynamic.

**Comment by meteos77** [comment] 2022-08-26 16:17
In my 4 tests

line 1 price = 20.12 OK (point and without symbol)
line 2 price = 20,34 OK ( coma and without symbol)
line 3 price = 20.56 $ KO (point and with a $)
line 4 price = 20.78 € OK (coma and with a €)

as far as I understand, it only removes the symbol defined with the locale and not all the currency symbols.

**Comment by meteos77** [comment] 2022-08-26 16:20
for me the problem was rather in the other direction

import without symbol => OK because monetary_unit defines the currency
export -> add a symbol which can be wrong (€ instead of $ or especially € instead of Fr for Francs)

**Comment by textbrowser** [comment] 2022-08-26 16:40
> In my 4 tests
> 
> line 1 price = 20.12 OK (point and without symbol) line 2 price = 20,34 OK ( coma and without symbol) line 3 price = 20.56 $ KO (point and with a $) line 4 price = 20.78 € OK (coma and with a €)
> 
> as far as I understand, it only removes the symbol defined with the locale and not all the currency symbols.

For sure. I suppose you want it to pick out the price from an infinite list of possibilities? Like, "$$$          30   .            ab25".

**Comment by textbrowser** [comment] 2022-08-26 16:42
The export cannot be wrong unless your locale is wrong. The export is of the things you see in  the main UI table. If you see currency symbols, they'll be exported. If any text contains a comma, it will be encased by double quotes.

**Comment by meteos77** [comment] 2022-08-26 16:59
I summarize what I have understood
- the import accepts the point and the comma (great)
- the import accepts the local currency symbol (linked to the principle import is equal to export)


so my question : 
I don't see why BQ put a € symbol in the UI table when the book is in Francs (old French currency), information provided in monetary_units.

1 €uros = 6,55959 Francs so no relation between the 2

**Comment by meteos77** [comment] 2022-08-26 17:04
example : 9782878332278
in zone 20 $c unimarc
35 FRF (French Francs)

all books sold in France before 2002 will be like that with FRF

in 2002 the European Union created a common currency the €uros

**Comment by meteos77** [comment] 2022-08-26 17:10
a quick extract of the books published before 2002 in my library: about 30% of documents concerned by a purchase in FRF

**Comment by meteos77** [comment] 2022-08-26 17:14
I don't know how easy it is to do

take what is in monetary_unit is if €uros or Euros
put € in UI table otherwise put nothing
the europeans will be that it is their currency before the euros

**Comment by meteos77** [comment] 2022-08-26 17:32
an example is more visible
the first 3 books are bought with Francs (F)
the 4th was in F/€ so I put euros

[exemple-Francs_Euros.sqlite.tar.gz](https://github.com/textbrowser/biblioteq/files/9435176/exemple-Francs_Euros.sqlite.tar.gz)

**Comment by textbrowser** [comment] 2022-08-26 17:43
> I summarize what I have understood
> 
>     * the import accepts the point and the comma (great)
> 
>     * the import accepts the local currency symbol (linked to the principle import is equal to export)
> 
> 
> so my question : I don't see why BQ put a € symbol in the UI table when the book is in Francs (old French currency), information provided in monetary_units.
> 
> 1 €uros = 6,55959 Francs so no relation between the 2

That's QLocale.

**Comment by textbrowser** [comment] 2022-08-26 17:46
Monetary Units and Price are totally separate. The price field in the UI may or may not contain a currency symbol; it depends upon QLocale. The Monetary Units value is a value which someone may or may not provide and if the unit differs from the currency symbol, BQ can do nothing about that.

**Comment by textbrowser** [comment] 2022-08-26 17:50
For Example, I may have a Japanese title with a price in dollars but a monetary unit of Yen. Thinking about this, I will remove the currency symbol from the UI.

**Comment by textbrowser** [comment] 2022-08-26 17:50
And display the value (without the symbol) in the locale.

**Comment by textbrowser** [comment] 2022-08-26 17:54
Done and that's enough BQ for today!

**Comment by meteos77** [comment] 2022-08-26 17:56
I agree with you; you have solved the problems presented well.
Thanks for the progress.

**Comment by meteos77** [comment] 2022-08-26 18:03
good end of day

**Comment by textbrowser** [comment] 2022-08-26 18:23
Yes, go to bed!

**Comment by meteos77** [comment] 2022-08-29 10:57
Summary of the "price" situation

- the French numeric keyboard has a key that makes a dot (European major)
- the fr_FR locale requires a comma in the price field. (display)
- the QDoubleSpinBox widget in the price field asks for a comma (input ui)
- biblioteq asks for a dot in the price field (database)

[I found a site that tells a portuguese how to do it](https://stackoverflow.com/questions/42534378/c-qt-creator-how-to-have-dot-and-comma-as-decimal-separator-on-a-qdoubles). 

if that gives you an idea.

Ideally, the dot on the numeric keypad should be accepted by the QDoubleSpinBox to fill the price
(situation of all software (LibreOffice, Calculator).
after BQ's internal cooking is not the user's concern :-) if BQ wants to have only points it doesn't bother us!

**Comment by textbrowser** [comment] 2022-08-29 11:22
Can you pull and rebuild? Submitted a book test.

**Comment by meteos77** [comment] 2022-08-29 11:40
the import works like a charm
OK with 12,12
OK with 12,12 €.
KO with 12,12 $ (normal it's not the local)

**Comment by textbrowser** [comment] 2022-08-29 11:46
And the book UI?

**Comment by meteos77** [comment] 2022-08-29 11:52
the price field has always had a comma

**Comment by meteos77** [comment] 2022-08-29 11:54
bookUI = 
![Capture du 2022-08-29 13-52-55](https://user-images.githubusercontent.com/56431039/187195171-88d175e6-57b9-43bc-bcaf-7d6b5e678100.png)
the price field has always had a comma

**Comment by textbrowser** [comment] 2022-08-29 11:54
You want a translation of the dot character? So if I press '.' in the widget, it should become a locale separator?

**Comment by meteos77** [comment] 2022-08-29 11:56
currently the numeric keyboard works but the French keyboard card of the numeric keyboard is a .

in your case can you enter a price with decimal only with the numeric keyboard?
we, we can not do it

**Comment by meteos77** [comment] 2022-08-29 11:58
we must use the ? key, (see keyboard image above)
which is not common in software that handles numbers
opencalc, calculator because as the locale is , and the numeric keyboard is made to enter numbers, the softwares transform the . of the numeric keyboard into , (decimal separator)

**Comment by textbrowser** [comment] 2022-08-29 11:59
Did you try enabling Num Lock?

**Comment by meteos77** [comment] 2022-08-29 12:02
calculator tool 
![outils-calculatrice](https://user-images.githubusercontent.com/56431039/187196612-3a2a71ce-352c-4aa1-a6f5-15771ab24ce0.png)
in this tool, if I want to have a decimal number, 
I can using only the numeric keyboard (numlock activated of course)

**Comment by meteos77** [comment] 2022-08-29 12:04
this is the problem explained in the 2 links provided today (Portuguese and French)

**Comment by textbrowser** [comment] 2022-08-29 12:05
For me to intercept the key press and map it to another key:
1. Create a custom sub-class.
2. Place the class in all UI files.
3. Build the sub-class.

Or.

1. Create a special filter class.
2. Add the filter class everywhere where a price field exists.

This is a lot of work for a price field.

**Comment by textbrowser** [comment] 2022-08-29 12:06
Since you can enter the price using the keyboard, the software works. Remember, BQ is not a point-of-sale application.

**Comment by meteos77** [comment] 2022-08-29 12:08
no worries, look at the title (small problems)

don't forget that I never know if it's 1 line or three hours of work disturbing my requests.

**Comment by meteos77** [comment] 2022-08-29 12:09
the import works with the comma that's the main thing

**Comment by meteos77** [comment] 2022-08-29 12:43
I would like to take into account the international context of use of the BiblioteQ software :-) which needs an improvement but whose development would require a time much too long for the immediate gain of the users.
The users are waiting for other evolutions more necessary for their use of the software.

**Comment by textbrowser** [comment] 2022-08-29 12:45
This quirky request is specific to your input device. Your input device displays represents a period. Why should the software translate a period into a comma?

**Comment by textbrowser** [comment] 2022-08-29 12:46
There are numerous keyboards without numeric pads. I don't have numeric pads on most of my keyboards. Laptops do not generally include numeric pads.

**Comment by textbrowser** [comment] 2022-08-29 12:47
Besides, the appropriate solution should be optional. Like, "Translate Numeric Pad Period".

**Comment by textbrowser** [comment] 2022-08-29 12:50
The calculator application has separate aspects. It's made for computing values so a bit of translating of a single character in a single location is natural. For BQ, it's not natural.

**Comment by meteos77** [comment] 2022-08-29 12:52
because we are French sir :-)
if you are ill-equipped :-) I have a laptop with numeric keypad.

in English you don't have accented letters like in many languages for example é è ê â ô ö ç ù for French so you don't need less keys, or we should have shortcuts without direct access to these characters

**Comment by textbrowser** [comment] 2022-08-29 13:02
There's a comma on your keyboard.

**Comment by meteos77** [comment] 2022-08-29 13:02
you are right, I will note the applications that make the difference

libreoffice -> coma

calculator -> coma
gimp -> dot
scribus -> dot
thunderbird -> point
firefox -> point

**Comment by textbrowser** [comment] 2022-08-29 13:04
> you are right, I will note the applications that make the difference
> 
> libreoffice -> coma
> 
> calculator -> coma gimp -> dot scribus -> dot thunderbird -> point firefox -> point

For numeric pad only, yes?

**Comment by textbrowser** [comment] 2022-08-29 13:06
Now, for the applications which are translating the dot to a comma on the numeric pad, which ones have this translation as an option? Also, what happens if you copy a value such as 55.55 and paste it into those applications? Do they translate the period into a comma?

**Comment by meteos77** [comment] 2022-08-29 13:07
options in libreoffice
![Libreoffice](https://user-images.githubusercontent.com/56431039/187207427-eaa01612-2c70-4cb7-b81b-b45bbc42651d.png)

**Comment by meteos77** [comment] 2022-08-29 13:08
no, it stays in point 
it does not allow to make calculation with it is a text field in librecalc

**Comment by meteos77** [comment] 2022-08-29 13:11
the good programs respect the language, the others are based on the Anglo-Saxon system.

**Comment by textbrowser** [comment] 2022-08-29 13:16
Like, if I see a key and I press the key I expect one or two things: the key is not understood because of some quirky application specifics or the key is understood and its interpretation is displayed. I don't expect a translation unless the application has made me aware of  the translation or I programmed my keyboard to translate or I modified the software to do so.

If I sit at a computer and type, I expect my key presses to be interpreted correctly regardless of what I'm typing into. Different expectations for POS machines, but even those have non-quirky behavior because they have to be? Correct!

**Comment by meteos77** [comment] 2022-08-29 13:17
my thought would be to align on a single system, the . or the comma but that the 5 continents agree on a way and everyone applies the same rule. this would avoid many unnecessary complications.

ditto for marc21 and unimarc

**Comment by meteos77** [comment] 2022-08-29 13:18
the weirdness concerns other countries (maybe even the majority of the world)

the question of Portuguese (Brazil) in the 1st link

the keyboard manufacturers do not respect the local weirdness as you say.
the point for the end of a sentence but as soon as it's decimal it's a comma so the numeric keyboard of Europeans should have a comma instead of a point, that would be more logical.

thanks for this discovery :-)

**Comment by textbrowser** [comment] 2022-08-29 13:20
Are you familiar with bc?

Terminal:
> bc

bc
bc 1.07.1
Copyright 1991-1994, 1997, 1998, 2000, 2004, 2006, 2008, 2012-2017 Free Software Foundation, Inc.
This is free software with ABSOLUTELY NO WARRANTY.
For details type `warranty'. 
55.55*2.0
111.10
55,55*2,0
(standard_in) 2: syntax error
(standard_in) 2: syntax error

**Comment by textbrowser** [comment] 2022-08-29 13:21
Does bc translate the dot from the numeric pad into a comma? If it does, that's bad.

**Comment by meteos77** [comment] 2022-08-29 13:22
bc only takes the point

**Comment by textbrowser** [comment] 2022-08-29 13:23
Which is the proper action.

**Comment by textbrowser** [comment] 2022-08-29 13:24
Aha, you're asking for context-sensitive translations which are annoying. If you're in this mode, the period is a comma. But what if you really want a period? Like, suppose you're in a numeric field and you want 55,000,000.55. And imagine you paste that. The application has to understand exactly what you want.

**Comment by meteos77** [comment] 2022-08-29 13:26
in the English context 55,000,000.55 does not exist in French
it is 55,000,000.55 or 55000000.55

**Comment by textbrowser** [comment] 2022-08-29 13:27
Also, imagine you have a value like 55,109230192301923 in your magical calculator and you want to paste that into bc. Can't. The buffer contains a comma and bc dislikes the comma. So, the application has to modify the contents of the buffer to replace the comma to a dot. But it should not do that unless you're pasting into an application which expects a dot. It can't do that because it doesn't know the destination.

**Comment by meteos77** [comment] 2022-08-29 13:30
this only means that the bc tool does not take the language into account.

**Comment by textbrowser** [comment] 2022-08-29 13:31
Do you have a French mathematics book which has decimal numbers? How are they represented?

**Comment by textbrowser** [comment] 2022-08-29 13:32
I have one in Spanish. Let me go find it.

**Comment by meteos77** [comment] 2022-08-29 13:38
![exemple-book](https://user-images.githubusercontent.com/56431039/187214346-3d424bba-79e9-4133-b8c3-7871b16918fc.jpg)

**Comment by meteos77** [comment] 2022-08-29 13:41
https://www.mathslibres.com/decimaux/multiplication_divers_nombs_x_2_dixiemes_001.php

**Comment by meteos77** [comment] 2022-08-29 13:55
https://www.smartick.com/blog/other-contents/curiosities/decimal-separators/

**Comment by meteos77** [comment] 2022-08-29 14:03
[an overview (world map)](https://i.redd.it/omgfapht3qn51.png)

**Comment by meteos77** [comment] 2022-08-29 14:05
thank you for making me interested in the subject decimal separator in the world :-)

**Comment by textbrowser** [comment] 2022-08-29 14:29
I suspect that period is more optimal than a comma in terms of pixels in printed materials.

**Comment by textbrowser** [comment] 2022-08-29 14:30
Let me search for the book again.

**Comment by meteos77** [comment] 2022-08-29 14:31
and a saving to print on the x billion keyboards in the world it's good for the planet, so we should generalize the point !

**Comment by textbrowser** [comment] 2022-08-29 14:34
Or standardize key caps and switches so that key caps can be easily removed and replaced. Keyboard enthusiasts.

https://www.newyorker.com/tech/annals-of-technology/the-obsessive-pleasures-of-mechanical-keyboard-tinkerers

**Comment by meteos77** [comment] 2022-08-29 14:49
![une-vrai-clavier](https://user-images.githubusercontent.com/56431039/187229403-9de2e25b-03f0-4b19-a6d1-605ae3c27495.jpg)
[a real keyboard](https://www.cherry.fr/cherry-g80-11900-touchboard.html)

**Comment by meteos77** [comment] 2022-08-29 14:59
![K650-Logitech](https://user-images.githubusercontent.com/56431039/187231542-a4abe93e-5ca9-4a76-a3a0-1c6d6436d573.jpg)

a new product from logitech
the K650, I just found my future keyboard not too expensive (50€)

**Comment by textbrowser** [comment] 2022-08-29 15:12
Logitech is generally expensive garbage.

Real keyboards?

https://www.zsa.io/moonlander/accessories/

**Comment by textbrowser** [comment] 2022-08-29 15:13
https://hhkeyboard.us/

**Comment by textbrowser** [comment] 2022-08-29 15:14
https://www.duckychannel.com.tw/en/Keyboards

**Comment by textbrowser** [comment] 2022-08-29 15:17
And of course, the Model M.

https://www.pckeyboard.com/page/product/NEW_M

https://en.wikipedia.org/wiki/List_of_mechanical_keyboards

**Comment by textbrowser** [comment] 2022-08-29 15:24
> ![K650-Logitech](https://user-images.githubusercontent.com/56431039/187231542-a4abe93e-5ca9-4a76-a3a0-1c6d6436d573.jpg)
> 
> a new product from logitech the K650, I just found my future keyboard not too expensive (50€)
> 
>     * no windows key and all characters are represented and see numeric keyboard with . and ,

Cherry switches are the best of the best.

**Comment by textbrowser** [comment] 2022-08-29 15:25
Is the metric system the optimal system in the Universe?

**Comment by meteos77** [comment] 2022-08-29 15:47
[my current keyboard is a cherry KC1000 and I am satisfied.](https://www.cherry.fr/cherry-kc-1000.html)

[on the subject (metric) you are quite alone in the world](https://fr.wikipedia.org/wiki/Fichier:Metrication_by_year_map.svg)

**Comment by textbrowser** [comment] 2022-08-29 15:53
No way. Metric is the best.

https://en.wikipedia.org/wiki/Metrication#/media/File:Metric_and_imperial_systems_(2019).svg

The US is screwed up.

There are exceptions.

https://www.nist.gov/pml/owm/metric-si

**Comment by meteos77** [comment] 2022-08-29 16:13
the world is different from the universe ; so there is still a doubt

US  : you can evolve quickly, it is a dynamic country (seen from outside)

**Comment by textbrowser** [comment] 2022-08-29 16:16
You should purchase an ergonomic keyboard for the library, or request that one be purchased, or request a fund be prepared for one. I have many recommendations.

**Comment by meteos77** [comment] 2022-08-29 16:16
https://www.sciencedirect.com/science/article/pii/S1631070518301695

I have no experience with any other system so it's hard for me to imagine how people in the US do it

**Comment by meteos77** [comment] 2022-08-29 16:18
library efficiency = hand shower  ; but I'm interested in your recommendations

**Comment by textbrowser** [comment] 2022-08-29 16:20
For basic measurements in inches, the US system is adequate. I can <see> an inch, a quarter of an inch, etc. For volumes... awful. Quarter of a cup? Half a cup? A cup is relative. So you need an official cup to have a cup.

**Comment by textbrowser** [comment] 2022-08-29 16:24
Some historians / geopolitical specialists have suggest(ed) that the geography of the US is what makes it a Super Power. It has relatively weak bordering countries, lots of resources, and is surrounded by water. Most of the world's other countries are not so fortunate.

**Comment by meteos77** [comment] 2022-08-29 16:26
At the right time, they were able to build a country that took over the entire continent.

**Comment by meteos77** [comment] 2022-08-29 16:30
your measuring system is not terrible

![regle-pouce-metric](https://user-images.githubusercontent.com/56431039/187249485-087f5098-fc93-4d1f-8ca9-0cf356aa9f04.png)

**Comment by meteos77** [comment] 2022-08-29 16:35
very good idea: the thumb goes back to the Middle Ages so effectively the person always had a rule in practice on it

**Comment by textbrowser** [comment] 2022-08-29 16:37
I prefer metric and can tolerate US.

**Comment by meteos77** [comment] 2022-08-29 16:42
I hope that the humans of the 21 and 22 centuries who will make the rules in the future will take into account the globalization and will remove the things of the past that complicate a lot of things for nothing.

the number of words, does not necessarily represent the difficulty of the language.
for me, who is not a specialist of English, it seems much easier than French to learn.

**Comment by textbrowser** [comment] 2022-08-29 16:45
I hope we're replaced by emotional robots.

**Comment by meteos77** [comment] 2022-08-29 16:54
isn't the keyboard an obsolete device?
In the past, I thought it would disappear and that we would run a computer by voice (faster).

le clavier n'est il pas un périphérique obsolète ?
dans le passé, je pensais qu'il allait disparaitre et que nous dirigerions un ordinateur pas la voix. (plus rapide).

**Comment by textbrowser** [comment] 2022-08-29 17:02
Yes, keyboards are not optimal.

**Comment by meteos77** [comment] 2022-08-29 17:03
![giphy](https://user-images.githubusercontent.com/56431039/187254683-f34e395a-f434-4961-896d-3b5d8c6c199b.gif)

**Comment by textbrowser** [comment] 2022-08-29 17:03
Nor are mice.

**Comment by meteos77** [comment] 2022-08-29 17:05
difference between mouse and mice  please ?

**Comment by meteos77** [comment] 2022-08-29 17:10
"le poêle" is "a stove",  while "la poêle" is a "frying pan
in fact you have words while the French has an article to differentiate.an »
and characters like ^ on vowels

**Comment by textbrowser** [comment] 2022-08-29 17:12
Two mouses. :)

**Comment by meteos77** [comment] 2022-08-29 17:25
1 souris ;  2 souris :-)

**Comment by meteos77** [comment] 2022-08-29 17:30
Thank you for spending part of the day, for opening up to a different world : it is always enriching.

good end of day

**Comment by meteos77** [comment] 2022-08-29 17:36
subsidiary question : By the way, where you live, does the mouse "chirp" when it makes noise?
What is the verb for noise?

I think that the translator is not going to be good on the subject :-)

**Comment by textbrowser** [comment] 2022-08-29 17:37
I think a mouse squeaks.
Birds chirp.

**Comment by textbrowser** [comment] 2022-08-29 17:38
Have a pleasant evening too!

**Comment by textbrowser** [comment] 2022-09-28 14:09
Done!

**Closed by textbrowser** 2022-09-28 14:09 UTC
Labels: bug, enhancement, a-lot-of-content

**Comment by meteos77** [comment] 2022-10-10 11:39
very small detail
- When creating a grey literature record :  the "Save" button at the bottom left is correctly translated as "Enregistrer".

- If you edit the same grey literature record : the "Save" button at the bottom left remains "Save".

**Comment by textbrowser** [comment] 2022-10-10 14:43
https://github.com/textbrowser/biblioteq/commit/34ded78dd52bafba0125591788d7ab125763a090

**Comment by meteos77** [comment] 2022-10-22 08:29
The book search does not seem to be taken into account on the field: "Multi-Volume Set ISBN".

Can you add this option ? Thank you in advance

**Comment by textbrowser** [comment] 2022-10-22 13:28
It's already included.

**Comment by textbrowser** [comment] 2022-10-22 13:42
And corrected. Caused by someone requesting that ISBNs be displayed in special formats.

**Comment by meteos77** [comment] 2022-10-22 14:34
` Caused by someone requesting that ISBNs be displayed in special formats`.
someone has to ask :-) it works thanks for the modification.
